Add swesar uavsar
bair-climate-initiative/metaearth pull request #15
Opened 2022-09-02 20:20 UTC by ShihengDuan

2022-09-02 22:44 UTC, ShihengDuan commented
The notebook should be good now.

2022-09-02 23:47 UTC, cjrd requested changes

2022-09-02 23:47 UTC, cjrd commented on config/nsidc-aso.yaml
> +  # ASO_50M_SD:
I think it's best to leave these uncommented

2022-09-03 00:45 UTC, cjrd approved these changes

2022-09-03 00:45 UTC, merged