Added sen2 config and notebook test
bair-climate-initiative/metaearth pull request #17
Opened 2022-09-02 22:49 UTC by RaymondMoo

2022-09-03 04:06 UTC, cjrd requested changes
2 issues:

1. The notebook is still pulling down 200+ mb, which is too much for a test. Do they have a demo/preview image that we could pull down?

2. There's an error here(?)
![image](https://user-images.githubusercontent.com/1455579/188255232-ac7d9935-d019-4d55-b2f5-5e6041ba792f.png)

2022-09-03 04:06 UTC, cjrd commented on setup.cfg
> +    pystac_client>=0.4,<1
did you try out pystac_client version 0.5?

2022-09-05 19:47 UTC, RaymondMoo commented on setup.cfg
> +    pystac_client>=0.4,<1
Nope! Not sure where that came from, reverted to main.

2022-09-06 16:11 UTC, cjrd approved these changes

2022-09-06 16:13 UTC, merged